openapi: '3.0.2'
info:
  title: Main Server
  description: API pour la gestion des actions liées à la gestion des Game Servers
  version: '1.0'
servers:
  - url: https://main.aw.alexandre-vogel.fr/


tags:
  - name: Serveurs
    description: Ensemble des fonctions liées aux serveurs

paths:
  /GameServer:
    post:
      tags: 
        - Serveurs
      summary: Permet l'ajout d'un nouveau serveur de jeu
      description: Ajout d'un nouveau serveur de jeu
      parameters:
        - in: header
          name: userToken
          schema:
            type: string
          required: true
          description: Token pour identifier l'utilisateur
      requestBody:
        content:
          json:
            schema:
              required:
                - name
                - address
                - port
              properties:
                name:
                  type: string
                  example: ServerName
                  description: Nom unique du serveur
                address:
                  type: string
                  example: 127.0.0.1
                  description: Adresse IP du serveur
                port:
                  type: number
                  example: 3030
                  description: Port du serveur
      responses:
        '200':
          description: Un nouveau serveur a bien été créé
        '401':
          description: L'utilisateur n'a pas les droits
        '402':
          description: Port déjà utilisé
        '403':
          description: Nom du serveur déjà existant
        '404':
          description: Paramètre(s) manquant(s) ou invalide(s)
        '500':
          description: Erreur interne au serveur
          
    delete:
      tags: 
        - Serveurs
      summary: Permet la suppression d'un serveur de jeu
      description: Suppression d'un serveur de jeu
      parameters:
        - in: header
          name: userToken
          schema:
            type: string
          required: true
          description: Token pour identifier l'utilisateur
      requestBody:
        content:
          json:
            schema:
              required:
                - name
              properties:
                name:
                  type: string
                  example: ServerName
                  description: Nom unique du serveur
      responses:
        '200':
          description: Le serveur a bien été supprimé
        '400':
          description: Paramètre(s) manquant(s) ou invalide(s)
        '401':
          description: Token invalide
        '402':
          description: L'utilisateur n'a pas les droits
        '403':
          description: Le serveur n'existe pas
        '500':
          description: Erreur interne au serveur
          
    put:
        tags:
          - Serveurs
        summary: Modifie le nombre de joueurs sur un serveur
        description: Permet de modifier, lors de l'arrivée ou du départ d'un joueur, le nombre de joueurs d'un serveur
        parameters:
          - in: header
            name: serverToken
            schema:
              type: string
            required: true
            description: Token pour identifier un serveur
        requestBody:
          content:
            json:
              schema:
                required:
                  - name
                  - playersNB
                properties:
                  name:
                    type: string
                    example: ServerName
                    description: Nom unique du serveur
                  playersNB:
                    type: string
                    example: -1 
                    description: Nombre de joueurs à ajouter/soustraire
        responses:
          "200":
            description: "Le nombre de joueurs a bien été modifié"
          "400":
            description: "Token invalide"
          "500":
            description: "Erreur serveur interne"
  
  /alive:
    post:
      tags:
        - Serveurs
      summary: Vérifie que le Main Server est toujours vivant
      description: Reçoie une liste de tokens et vérifie qu'il s'agit bien d'un serverToken valide
      requestBody:
        content:
          json:
            schema:
              type: array
              description: Liste de tokens des Games Servers vivants
              properties:
                serverToken:
                  type: string
                  example: 7dea256198bb51e501ee2d18da735a006e85ef00d6fde30dbd4c141490db9dc8
                  description: Token pour identifier un serveur
      responses:
        "200":
          description: "Le Main Server est toujours opérationnel"
        '400':
          description: Paramètre(s) manquant(s) ou invalide(s)
        "401":
          description: "Token invalide"
        "500":
          description: "Erreur serveur interne"

  /list:
    get:
      tags:
        - Serveurs
      summary: Récupère la liste des Game Servers avec leurs informations
      description: Récupère la liste des Game Servers avec leurs informations
      parameters:
        - in: header
          name: userToken
          schema:
            type: string
          required: true
          description: Token pour identifier l'utilisateur
      responses:
        "200":
          description: L'ensemble des Game Servers a été récupéré
          content:
            json:
              schema:
                type: array
                description: Liste des Game Servers contenant leur nom, leur nombre de joueurs, leur adresse IP et leur numéro de port
                items:
                  $ref: '#/components/schemas/server_list'
        "401": 
          description: Token invalide
        "500":
          description: Internal Server Error
    
components:
  schemas:
    server_list:
      type: object
      properties:
        servername:
          type: string
          example: server1
          description: Nom du serveur
        nb_user:
          type: number
          example: 3
          description: Nombre de joueur sur le serveur
        address:
          type: string
          example: 127.4.5.8
          description: Adresse IP du serveur
        port:
          type: number
          example: 3066
          description: Port du serveur

